create column table currency (
    
   id int primary key generated by default as IDENTITY,
   iso_code nvarchar(5),
   symbol nvarchar(10),
   unicode nvarchar(25),
   position_ nvarchar(20),
   comments nvarchar(255) 

);

insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values('USD','$','&#36;','before','');
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('EUR','€','&#128;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CAD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('GBP','£','&#163;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('AUD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('AED','د.إ','','after','Can not find'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('ANG','ƒ','&#x0192;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('AOA','AOA','AOA','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('ARS','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('BAM','KM','KM','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('BBD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('BGL','лв','&#1083;&#1074;','before','ISO code is actually BGN'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('BHD','BD','BD','after',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('BND','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('BRL','R$','R&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CHF','Fr','Fr','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CLF','UF','UF','after',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CLP','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CNY','¥','&#165;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('COP','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CRC','₡','&#x20A1;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('CZK','Kč','K&#269;','after',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('DKK','kr','kr','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('EEK','KR','KR','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('EGP','E£','E&#163;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('FJD','FJ$','FJ&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('GTQ','Q','Q','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('HKD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('HRK','kn','kn','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('HUF','Ft','Ft','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('IDR','Rp','Rp','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('ILS','₪','&#x20AA;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('INR','Rs','Rs','before','There is not a unicode'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('JOD','د.ا','','','Can not find'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('JPY','¥','&#165;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('KES','KSh','Ksh','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('KRW','₩','&#x20A9;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('KWD','KD','KD','after',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('KYD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('LTL','Lt','Lt','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('LVL','Ls','Ls','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('MAD','د.م.','','','Can not find'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('MVR','Rf','Rf','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('MXN','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('MYR','RM','RM','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('NGN','₦','&#x20A6;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('NOK','kr','kr','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('NZD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('OMR','OMR','&#65020;','after','Unsure if this is correct'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('PEN','S/.','S/.','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('PHP','₱','&#x20B1;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('PLN','zł','Z&#322;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('QAR','QAR','&#65020;','after','Unsure if this is correct'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('RON','lei','lei','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('RUB','руб.','&#1088;&#1091;&#1073;','after',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('SAR','SAR','&#65020;','after','Unsure if this is correct'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('SEK','kr','kr','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('SGD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('THB','฿','&#322;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('TRY','TL','TL','before','There is not a unicode'); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('TTD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('TWD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('UAH','₴','&#8372;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('VEF','Bs F','Bs.','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('VND','₫','&#x20AB;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('XCD','$','&#36;','before',''); 
insert into "TEST_DB"."CURRENCY"("ISO_CODE","SYMBOL", "UNICODE","POSITION_","COMMENTS") values ('ZAR','R','R','before','')